---
- name: Parcha un conjunto de servidores linux
  # A quienes se les va a operar 
  hosts: all
  tasks:
    - name: Asegurarse de que el sistema está actualizado
      dnf:
        name: "*"
        state: latest
